<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="EffectParameters.cs" />
    <Compile Include="NotifyPropertyChangedBase.cs" />
    <Compile Include="ParameterValueTranslator.cs" />
    <Compile Include="Patch.cs" />
    <Compile Include="SysExMessages.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="SysExMessages.cs" />
  </ItemGroup>

</Project>
